name: Android CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "README.md"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Write key
        if: ${{ github.event_name != 'pull_request' || github.ref_type == 'tag' }}
        run: |
          if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
            echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
            echo androidKeyAlias='ghhccghk' >> local.properties
            echo androidKeyPassword='${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
            echo androidStoreFile=`pwd`/key.jks >> local.properties
            echo ${{ secrets.SIGNING_KEY }} | base64 --decode > key.jks
          fi

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'jetbrains'
          cache: gradle

      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Set release type
        run: echo releaseType=GitHub CI > package.properties

      - name: Build with Gradle
        run: |
          ./gradlew assemble
          ./gradlew bundleRelease

      - name: Find APKs
        id: apks
        run: |
          echo "list=$(ls app/build/outputs/apk/release/*.apk | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Upload each APK
        uses: actions/upload-artifact@v4
        strategy:
          matrix:
            apk: ${{ fromJson(steps.apks.outputs.list) }}
        with:
          name: ${{ matrix.apk }}
          path: ${{ matrix.apk }}

      - name: Upload Release Mapping
        uses: actions/upload-artifact@v4
        with:
          name:  Record Echoes mapping
          path: ./app/build/outputs/mapping/release/mapping.txt
